= cPP Lifecycle for the Biometrics Security iTC
:showtitle:
:toc:
:toclevels: 3
:table-caption: Table
:imagesdir: images
:revnumber: 0.1
:revdate: 2020-08-11
:xrefstyle: full

:iTC-longname: Biometrics Security
:iTC-shortname: BIO-iTC
:iTC-email: isec-itc-bio-info@ipa.go.jp
:iTC-website: https://biometricitc.github.io/
:iTC-GitHub: https://github.com/biometricITC/cPP-biometrics
:iTC-ITname: BIT

== Introduction
As part of the normal work of the {iTC-shortname}, new iterations of the cPP and SD will be released over time. Ideally, when a new version of the cPP is released, everyone would immediately follow the new version, but this is not possible as it takes time to transition to updated requirements.

The purpose of this document is to specify the lifecycle for cPP versions, providing guidance on when a new version will supersede earlier versions (when the previous version is no longer considered acceptable for use) and how this will be announced to the wider community.

[NOTE]
====
While the document talks about cPP revisions, this covers the cPP, SD, and any other related documents.
====

== Revision Classes
There are three classes of revisions to a cPP that can be produced. The descriptions are not meant to be exhaustive, but to represent the level of changes in the document.

.Revision Classes for a cPP
[cols=".^1,.^1,.^4",options="header"]
|===

|Revision Class
|Version Position
|Description

|Major
|**X**.y.zz
|Full update to the cPP, including requirements changes (i.e., addition or removal of requirements)

|Minor
|x.**Y**.zz
|Update to the cPP, likely updating existing requirements, but not changing them (i.e., not adding or removing requirements)

|Technical Decision or Errata
|x.y.**ZZ**
|Application of Technical Decisions to the cPP with no other changes

|===

=== Revisions & Branches
The {itc-shortname} maintains 3 primary branches for the creation of the cPP and all supporting documents. Of these branches, those shown in <<Branches & the Latest Documents>> will be used to maintain the current versions of the documents. The third branch and any additional branches are used for active work on new updates, but are not considered published.

.Branches & the Latest Documents
[cols=".^1,.^1,.^4",options="header"]
|===

|Branch
|Versions
|Description

|Master/Main
|**X**.**Y**
|This is always maintained at the latest Major.Minor release and is the "official" published version.

|Interpretation
|x.y.**ZZ**
|This branch will be updated for each TD that is published and is a rolling update for all approved TDs between Major.Minor updates.

This branch can be used in place of Major.Minor + TDs if the validating scheme approves all TDs.

|===

The {itc-shortname} may approve errata updates on a periodic basis to officially roll TDs into a published release depending on the number of TDs and the time before the next full update.

== Revision Transitions
When a new revision is published, it is immediately available for use. So if version 1.1 is released, it can be immediately used for an evaluation. To ensure a common direction and basis for evaluation within the community, the release of a new cPP revision means that the previous revisions must be retired from active use.

The transition period is a time of overlap when multiple revisions of the cPP may be used for an active evaluation. The transition periods are determined by the type of revision being published. At the end of the transition period, the previous revision will be retired and no longer be considered acceptable for new evaluations. Evaluations already in process may still be completed after the transition period for a revision has concluded.

The following table specifies when the previous revision will be retired and the new revision takes precedence.

.Transition Periods 
[cols=".^1,.^1",options="header"]
|===

|Revision Class
|Transition Period

|Major
.2+|6 months after the new revision is published

|Minor


|Technical Decision
|Immediate

|===

[IMPORTANT]
====
While the iTC may specify these time periods for the transitions between versions, a scheme may decide on different periods/dates for the transition between versions. The iTC may be able to influence the acceptance of the transition times, but it is a scheme decision.
====

=== Major & Minor Transitions
The practical implication of this transition period is that there should only be a 6 month overlap with multiple versions being available for use. The following diagram illustrates the time periods, showing the months from the initial release of v1.0 through to v2.0.

[#transitions]
[ditaa,transition,png]
....
/----------------------------\
|  cPP v1.0     cRED         |
\----------------------------/

                    /-----------------------\
                    |  cPP v1.1   cBLU      |
                    \-----------------------/

                                   /----------------------------\
                                   |  cPP v2.0    cGRE          |
                                   \----------------------------/

0                   12       18    22       28         Months
*-------------------*--------*-----*--------*------------------->
v1.0                v1.1           v2.0                Release

                             v1.0           v1.1       Retire
....

=== Technical Decision Transitions
By their nature, Technical Decisions are meant to take effect immediately. The one caveat to this is for evaluations where the checkout report has already been submitted to the scheme, at which point the Technical Decisions are not required to be added to the Security Target.
