= Biometrics Security Interpretation Team (BIT) Approvals
:showtitle:
:table-caption: Table
:revnumber: 0.1
:revdate: 2020-05-14

:iTC-longname: Biometrics Security
:iTC-shortname: BIO-iTC
:iTC-email: isec-itc-bio-info@ipa.go.jp
:iTC-website: https://biometricitc.github.io/
:iTC-GitHub: https://github.com/biometricITC/cPP-biometrics
:iTC-ITname: BIT

== {iTC-ITname} Technical Resolution Approvals
The goal of the {iTC-ITname} is to always reach a decision by consensus. That may not always be possible, but even when it is, the process for ensuring the changes are agreed to is handled by setting restrictions on the Interpretation branch in GitHub. 

The table below specifies the approval criteria for accepting a resolution from the {iTC-ITname}.

Within these numbers, the requirements of the ToR such as votes per organization, abstentions, etc., are in effect. 

Approvals that occur through the GitHub approval process are automatically recorded and do not need any external recording or process.

[cols=".^2,.^1,.^2,.^1,.^3",options="header"]
|====

|Category
|Type
|Approval
|By
|Description


|Technical Decision
|GitHub
|75%
^|{iTC-ITname}
|This is a normal approval within GitHub (of a pull request). There are no rejections or blocks on the change.

.2+|Technical Recommendation
|GitHub
|75%
^|{iTC-ITname}
|The {iTC-ITname} must first approve a change with no rejections or blocks on the change. The approved change will then be submitted to the entire {iTC-shortname} for approval.

|Offline (not GitHub)
|66% with fewer than 25% negative
^|iTC
|If the change has been determined to be sufficiently large or a consensus decision cannot be made by the {iTC-ITname}, the final determination will be done by the whole iTC.

|====

== Approval Process Note (At {iTC-ITname} launch)
The {iTC-shortname} will follow the Technical Recommendation approval process for all updates. This may be changed later by the {iTC-shortname} through the normal approval process as defined in the ToR.