= Biometric iTC Public Review Process
:showtitle:
:toc:
:toclevels: 3
:table-caption: Table
:revnumber: 1.0
:revdate: 2021-10-05
:xrefstyle: full

:iTC-longname: Biometrics Security
:iTC-shortname: BIO-iTC
:iTC-email: isec-itc-bio-info@ipa.go.jp
:iTC-website: https://biometricitc.github.io/
:iTC-GitHub: https://github.com/biometricITC/cPP-biometrics
:iTC-ITname: BIT

== Introduction
This is an overview of the public review process for the {itc-shortname}. While this process may be modified for specific documents, in general this process is followed for the review and release of all public documents needed for evaluation. This would cover the PP (PP-Module and PP-Configuration), the SD and any Toolbox documentation. While the PP and SD are generally done in parallel, it is possible for any documents to be undergoing the review process independently.

When any review process is started, the information regarding the expected steps and timelines will be included in the public review announcement.

== Document Review Process
The {itc-shortname} follows the document release process below for the publication of documents. This process may be adjusted depending on the expected level of changes being made, either to be shorter or longer by adjusting the number of public review draft cycles.

[ditaa]
....
                                  
    +----------+    +----------+   +----------+   +----------+   +----------+
    |          |    |  cYEL    |   | Public   |   |          |   | Public   |
    | Internal |    |  Public  |   | Review   |   |  Public  |   | Review   |
    |  Draft   |--> |  Review  |-->| Draft 1  |-->|  Review  |-->| Draft 2  |-+
    |          |    |  Draft 1 |   | Update   |   |  Draft 2 |   | Update   | |
    |          |    |  (45d)   |   | (60d)    |   |  (45d)   |   | (60d)    | |
    +----------+    +----------+   +----------+   +----------+   +----------+ |
                                                                              |
            +-----------------------------------------------------------------+
            |   +----------+   +----------+   +-----------+
            |   |          |   |          |   |           |
            |   | Proposed |   | Proposed |   | Final     |
            +-->|  Draft   |-->|  Update  |-->| Document  |
                |          |   |          |   | Published |
                | (30d)    |   | (10d)    |   |           |
                +----------+   +----------+   +-----------+
....

.Review Timeline
[[timeline]]
[cols=".^2,.^1,3",options="header"]
|===

|Phase 
|Time 
|Description

|Internal Draft
|
|The normal, pre-release process for creating the documents

|Public Review Draft 1
|45 days
|iTC has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

|Public Review Draft 1 Update
|Up to 60 days
|The iTC will review all received comments and update the documents accordingly

|Public Review Draft 2
|45 days
|iTC has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

PAD Toolbox drafts will be published with this review (final review on toolboxes may proceed independently from rest of documents).

|Public Review Draft 2 Update
|Up to 60 days
|The iTC will review all received comments and update the documents accordingly

|Public Review Draft 3 (Optional, not shown)
|45 days
|iTC has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

|Public Review Draft 3 Update (Optional, not shown)
|Up to 60 days
|The iTC will review all received comments and update the documents accordingly

|Proposed Draft
|30 days
|iTC has voted according to Terms of Reference to propose this as the final document. Public (i.e. from non-iTC participants) comments are accepted during this period

|Proposed Update
|10 days
|iTC reviews any further comments and prepares the document for final publishing (updating all dates, producing official versions for publication)

|Final Document Published
|
|Documents are posted to Common Criteria Portal

|===

The iTC may decide, based on the comments received during the Public Review Draft 1 period, that a Public Review Draft 2 period is needed. Public announcement of a second review draft or a proposed draft will be made once all comments have been addressed.