= Biometrics Security Submitting Toolbox Updates
:showtitle:
:table-caption: Table
:revnumber: 0.1
:revdate: 2020-12-17

:iTC-longname: Biometrics Security
:iTC-shortname: BIO-iTC
:iTC-email: isec-itc-bio-info@ipa.go.jp
:iTC-website: https://biometricitc.github.io/
:iTC-GitHub: https://github.com/biometricITC/cPP-biometrics
:iTC-ITname: BIT

== Introduction
The {itc-shortname} does not intend the PAD toolboxes to be static, and should be updated regularly. This can include new techniques for an existing modality or a completely new modality that has entered the market and has need of validation. This document is intended to provide guidance on how requests for updates should be made to the {itc-shortname}.

This is not intended to provide guidance on questions about the existing toolboxes, such as interpretations or other issues with the requirements which would be handled through the normal Interpretation process. Create a new issue by selecting {iTC-GitHub}/issues/new/choose[Request for Interpretation] for questions of this type.

== Types of Update Requests
There are three categories of update requests as defined by the table.

[cols=".^1,.^2,.^2,.^1",options="header"]
|====

|Category
|Description
|Expected Information to be Provided
|Rough Timeline

|Question/Issue with existing Toolbox
|Questions, need for interpretation on existing toolboxes
|Complete {iTC-GitHub}/issues/new/choose[Request for Interpretation] issue submission and follow the standard interpretation process.
|4 to 6 Weeks

|New test procedures to existing Toolbox
|Updates to an existing toolbox, such as adding a new test method, for example, adding a new set of materials and related attacks for the fingerprint toolbox.
|A {iTC-GitHub}/issues/new/choose[Request for Interpretation] and create new issues and pull requests in the appropriate toolbox to add the new information. The submission should be as complete as possible.

The review would follow the standard interpretation process.
|3 to 5 months

|Toolbox for new modality
|A completely new toolbox for a new modality
a|A https://github.com/biometricITC/cPP-toolboxes/issues/new/choose[New Modality request] to start the process. After agreement by the {itc-shortname} to add the modality, the requestor should provide a toolbox containing the following (at a minimum):

* Modality Overview
* Modality Inventory
* Modality References
* Modality Verification List
* Attacks (including attack potential calculations)

Once started, the process for adding the modality will follow the standard update/review cycle. Incomplete toolbox information that must be generated by the iTC will increase the time needed to complete the review period. The iTC expects the requesting party to be involved in the review process.
|6 to 10 months

|====

== New artefacts found

If the evaluator can find new artefact species, the evaluator shall consider the following factors to examine whether those new artefact species can be used in the actual operational environment or not.

[loweralpha]
. Attacker’s motivation
+
For enhanced security that is easy to use, the TOE implements biometric verification on a device once it has been “unlocked”. The initial unlock is generally done by a NBAF which is required at startup (or possibly after some period of time), and after that the user is able to use a registered biometric characteristic to unlock access to the computer. The BIOSD assumes that the biometric verification is being used in accordance with USE CASE 1: Biometric verification for unlocking the computer.
+
Attacker may use any tools or materials that are normally available at home and normal office environment such as laptop PC or office printer to attack the TOE. Attacker may also use any services (e.g. printing services to print a high-resolution photo of target users to create a face artefact) if such services are available at low cost.

[loweralpha, start=2]
. Assumptions and Objectives in <<PP_MD_V3.3>>
+
--
<<PP_MD_V3.3>> defines *A.CONFIG* and the evaluator shall assume that the computers are configured securely to enforce the TOE security policies and *A.PROPER_USER* where the evaluator shall assume that the user is not negligent or hostile. The evaluator shall make the following assumptions:

[arabic]
.. A user has enroled following guidance provided by the TOE
.. The computer is securely configured, and maximum number of unsuccessful biometric authentication attempts is limited
+
For efficiency, the evaluator can increase the maximum number of unsuccessful biometric authentication attempts to conduct the testing. However, as the computer shall be evaluated in the evaluated configuration, any attack needs to succeed within the allowed number of biometric authentication attempts defined in the ST to be considered a successful attack.

<<PP_MD_V3.3>> also defines *O.INTEGRITY* and the evaluator shall assume that biometric data is adequately protected. Especially the evaluator shall make the following assumptions:

[arabic, start=1]
.. Attacker can not access the results of PAD subsystem, so they can not tune the artefacts based on the PAD score
.. Attacker can not gain access to the templates from the computer to create the artefacts
--

[loweralpha, start=3]
. Attack potential
+
The evaluator is not expected to determine the exploitability for new artefact species beyond those for which a Basic attack potential is required to create and present. Therefore, the evaluator shall determine that attack potential required to use new artefact species is within the scope of the Basic attack potential referring <<Attack Potential and TOE resistance>>.

=== Produce test plan

The evaluator shall perform EAs in <<No new artefacts found test plan>> if there is no new artefact species found in previous step. Otherwise, follow <<New artefacts found test plan>>.

==== New artefacts found test plan

If the evaluator can find a new artefact species that can be used for penetration testing, the evaluator shall produce the test item for those new artefact species and add them to the <<Toolbox>>. The evaluator shall create those new test items at the same format and level of detail as existing items in the <<Toolbox>>.

Those new test items are out of scope of the independent testing, so the evaluator shall test them first during the penetration testing as described in <<Testing the new artefacts>>. 

The evaluator shall compare and select best candidates from artefacts in <<Toolbox>> and new ones so the evaluator shall apply EAs in <<No new artefacts found test plan>> to both artefacts. 

The evaluator shall inform the BIO-iTC if one can find those new artefacts that are worthwhile to test because the BIO-iTC is responsible for maintaining the <<Toolbox>>.

==== Testing the new artefacts 

This section is only applicable when the evaluator can find new artefacts at <<Search for new artefacts>>.

The evaluator shall test those test items created for new artefacts first following the same procedure as the one used for the independent testing and add them to the final test plan based on the result of this testing, as described in <<New artefacts found test plan>>.