= Biometrics Security Submitting Toolbox and Modality Updates
:showtitle:
:table-caption: Table
:revnumber: 0.2
:revdate: 2021-09-21

:iTC-longname: Biometrics Security
:iTC-shortname: BIO-iTC
:iTC-email: isec-itc-bio-info@ipa.go.jp
:iTC-website: https://biometricitc.github.io/
:iTC-GitHub: https://github.com/biometricITC/cPP-biometrics
:iTC-ITname: BIT

== Introduction
The {itc-shortname} does not intend the list of supported modalities or the associated PAD toolboxes to be static, and should be updated regularly. This can include new testing techniques for an existing modality or a completely new modality that has entered the market and has need of validation. This document is intended to provide guidance on how requests for updates should be made to the {itc-shortname}.

This is not intended to provide guidance on questions about the existing toolboxes, such as interpretations or other issues with the requirements which would be handled through the normal Interpretation process. Create a new issue by selecting {iTC-GitHub}/issues/new/choose[Request for Interpretation] for questions of this type.

While the descriptions here assume that an evaluator is providing the documentation, the {itc-shortname} does not require that updates be submitted solely by an evaluator. Any vendor or interested party may provide updates to be reviewed for approval (or rejection). 

== Types of Update Requests
There are three categories of update requests as defined by the table.

[cols=".^1,.^2,.^2,.^1",options="header"]
|====

|Category
|Description
|Expected Information to be Provided
|Rough Timeline

|Question/Issue with existing Toolbox
|Questions, need for interpretation on existing toolboxes
|Complete {iTC-GitHub}/issues/new/choose[Request for Interpretation] issue submission and follow the standard interpretation process.
|4 to 6 Weeks

|New test procedures or artefacts to existing Toolbox
|Updates to an existing toolbox, such as adding a new test method, for example, adding a new set of materials and related attacks for the fingerprint toolbox.
|A {iTC-GitHub}/issues/new/choose[Request for Interpretation] and create new issues and pull requests in the appropriate toolbox to add the new information. The submission should be as complete as possible.

The review would follow the standard interpretation process.
|4 to 6 weeks (initial approval expected for use)

3 to 5 months (total)

|Adding a new modality
|A completely new toolbox for a new modality
a|A https://github.com/biometricITC/cPP-toolboxes/issues/new/choose[New Modality request] to start the process. After agreement by the {itc-shortname} to add the modality, the requestor should provide a toolbox containing the following (at a minimum):

* Modality Overview
* Modality Inventory
* Modality References
* Modality Verification List
* Attacks (including attack potential calculations)

Once started, the process for adding the modality will follow the standard update/review cycle. Incomplete toolbox information that must be generated by the iTC will increase the time needed to complete the review period. The iTC expects the requesting party to be involved in the review process.
|6 to 10 months

|====

== Adding New Artefact Species Guidance
As part of the evalautor requirements, the evaluator must review current research and determine if new artefact species may be appropriate for the evaluation of a biometric system. If the evaluator finds new artefact species, the evaluator shall consider the following factors to examine whether those new artefact species can be used in the actual operational environment or not. 

=== Determining Species Applicability

. Attacker’s motivation
+
For enhanced security that is easy to use, the TOE implements biometric verification on a device once it has been “unlocked”. The initial unlock is generally done by a NBAF which is required at startup (or possibly after some period of time), and after that the user is able to use a registered biometric characteristic to unlock access to the computer. The BIOSD assumes that the biometric verification is being used in accordance with USE CASE 1: Biometric verification for unlocking the computer.
+
Attacker may use any tools or materials that are normally available at home and normal office environment such as laptop PC or office printer to attack the TOE. Attacker may also use any services (e.g. printing services to print a high-resolution photo of target users to create a face artefact) if such services are available at low cost.

[start=2]
. Assumptions and Objectives in <<PP_MD>>
+
--
<<PP_MD>> defines *A.CONFIG* and the evaluator shall assume that the computers are configured securely to enforce the TOE security policies and *A.PROPER_USER* where the evaluator shall assume that the user is not negligent or hostile. The evaluator shall make the following assumptions:

.. A user has enroled following guidance provided by the TOE
.. The computer is securely configured, and maximum number of unsuccessful biometric authentication attempts is limited
+
For efficiency, the evaluator can increase the maximum number of unsuccessful biometric authentication attempts to conduct the testing. However, as the computer shall be evaluated in the evaluated configuration, any attack needs to succeed within the allowed number of biometric authentication attempts defined in the ST to be considered a successful attack.

<<PP_MD>> also defines *O.INTEGRITY* and the evaluator shall assume that biometric data is adequately protected. Especially the evaluator shall make the following assumptions:

[start=1]
.. Attacker can not access the results of PAD subsystem, so they can not tune the artefacts based on the PAD score
.. Attacker can not gain access to the templates from the computer to create the artefacts
--

[start=3]
. Attack potential
+
The evaluator is not expected to determine the exploitability for new artefact species beyond those for which a Basic attack potential is required to create and present. Therefore, the evaluator shall determine that attack potential required to use new artefact species is within the scope of the Basic attack potential referring Attack Potential and TOE resistance in the BIOSD.

=== Produce Test Plan
If the new artefacts would meet the conditions above, the evaluator must create a test plan using the new artefacts that follows, to the extent possible, the format and structure of the existing plans for that modality in the exsting Toolbox. Any new plans should follow the same format and level of detail as the existing items within the modality Toolbox.

=== Active Evaluation New Artefact Approval Timeline
All artefact types must be approved by the {itc-shortname} to be included in the Toolbox. As this process can take a long time, the {itc-shortname} has established a two-stage process to minimize delays during an active evaluation.

[ditaa, approvaltimeline, png]
....
                                  
    +----------+   +----------+   +----------+   +----------+   +----------+
    |          |   |          |   |          |   |  New     |   |          |
    | Initial  |   |  Initial |   | Publish  |   |  Toolbox |   | Updated  |
    |Submission|-->|  Review  |-->| New      |-->|  Public  |-->| Toolbox  |
    |          |   |          |   | Toolbox  |   |  Review  |   |          |
    |          |   |  (4-6w)  |   | (1w)     |   |  (2-4m)  |   |          |
    +----------+   +----------+   +----------+   +----------+   +----------+

....

When the evaluator submits a new artefact for review, the {itc-shortname} will review the submitted package under an Interpretation Team style review. The outcome of this review, if the changes are accepted, will be to publish an update to the existing Toolbox for the modality that can be used for the active evaluation.

After this version has been published, the Toolbox change will undergo a full public review process for comments and possible further updates. The outcome of the public review may be to further refine the changes or to accept them as approved initially by the {itc-shortname}.

Once a new artefact has been published, all future evaluations must utilize the latest version of the Toolbox. 

==== Initial Review Expectations
The {itc-shortname} expects the evaluator to be responsive during the initial review process to ensure the ability to meet the accelerated timeline for approval of the changes. Any delays in reponding may cause the review period to stretch beyond the expected window.

==== New Artefact Rejection
After review, the {itc-shortname} may determine that a new artefact is not in scope of the requirements as specified in the current BIOPPM and BIOSD. In this case, the new artefacts cannot be used as part of an evaluation for any claims. This outcome will be provided at the end of the review period.

=== New Artefact Approval Timeline Without an Active Evaluation
If an evaluator provides a new artefact test plan without an associated active evaluation, the {itc-shortname} will utilize the normal https://github.com/biometricITC/Administration/Public_review_process.adoc[public review process] before updating the apporpriate Toolbox.